- name: crear directorio .ssh
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: 0700


- name: creando clave ssh
  copy:
    src: /var/lib/awx/projects/new_hosts/roles/crear_auth/files/authorized_keys
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: 0600 
